let api;
if (import.meta.env.DEV) {
	api = (await import("@backend/convex/_generated/api")).api;
} else {
	//@ts-ignore - file generated by CI for production
	api = (await import("@/lib/convexApi")).api;
}

export {api};